const ActionList = {
    FETCH_WEEKLY_ROASTER_DATA:'FETCH_WEEKLY_ROASTER_DATA',
    WEEKLY_ROASTER_SUCCESS:'WEEKLY_ROASTER_SUCCESS',
    WEEKLY_ROASTER_FAILED:'WEEKLY_ROASTER_FAILED',
    UNSET_ROASTER_STATE:'UNSET_ROASTER_STATE',
    FETCH_SHIFT_MAPPING_DATA:'FETCH_SHIFT_MAPPING_DATA',
    REDIRECT_MASTER_DATA_LOADED:'REDIRECT_MASTER_DATA_LOADED'
};
export default ActionList;