const ActionList = {
    FETCH_WEEKLY_ROASTER_DATA:'FETCH_WEEKLY_ROASTER_DATA',
    WEEKLY_ROASTER_SUCCESS:'WEEKLY_ROASTER_SUCCESS',
    WEEKLY_ROASTER_FAILED:'WEEKLY_ROASTER_FAILED',
    UNSET_ROASTER_STATE:'UNSET_ROASTER_STATE'
};
export default ActionList;